apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: terraform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: terraform
    spec:
      containers:
        - name: terraform
          image: 'hashicorp/terraform'
          ports:
            - containerPort: 80
          env:
            - name: KANBAN_SERVER_HOSTNAME
              value: "http://terraform.cisel.lan"
            - name: KANBAN_REDIS_ADDR
              value: "localhost:6379"
            - name: KANBAN_GITLAB_URL
              value: "https://gitlab.com"
            - name: KANBAN_GITLAB_CLIENT
              value: "CLIENT_ID"
            - name: KANBAN_GITLAB_SECRET
              value: "SECRET_ID"
            - name: KANBAN_ENABLE_SIGNUP
              value: "true"
        - name: redis
          image: 'leanlabs/redis:1.0.0'
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: terraform-service
  labels:
    name: terraform-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: terraform
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: terraform
  namespace: default
spec:
  rules:
  - host: terraform.cisel.lan
    http:
     paths:
      - path:
        backend:
          serviceName: terraform-service
          servicePort: 80